travis: switch to Python 3 version
- install python3 on mac machines
- run test-run without specifying path to python interpreter
- create symbolic link to python3 on FreeBSD
- set --test-timeout --> 200 (DEBUG)
- get rid our own tarantool brew-tap that depends on Python 2
- install python modules to users directory instead of system dirs. See below.

Installation of modules to a system directory is failed [1]:

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
Consider using the `--user` option or check the permissions.

To avoid this one should use option --user passed to pip.

1. https://gitlab.com/tarantool/tarantool/-/jobs/971934335

Part of #5652